version: '3.1'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-plataforma_cursos}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sua_senha}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    ports:
      - "5432:5432"
    
